import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

# -------------------------------------------------------------------
# STEP 1: Load and Inspect the Dataset
# -------------------------------------------------------------------
df = pd.read_csv('/content/supply_chain_data.csv')

print("--- Data Summary ---")
print(df.info())
print("\n--- Missing Values Check ---")
print(df.isnull().sum())

# -------------------------------------------------------------------
# STEP 2: Product & Revenue Performance Analysis
# -------------------------------------------------------------------
product_analysis = (
    df.groupby('Product type')
    .agg(
        total_revenue=('Revenue generated', 'sum'),
        total_units_sold=('Number of products sold', 'sum'),
        avg_price=('Price', 'mean'),
    )
    .reset_index()
)

print("\n--- Revenue Performance by Product Type ---")
print(product_analysis)

# -------------------------------------------------------------------
# STEP 3: Logistics & Carrier Cost Efficiency
# -------------------------------------------------------------------
carrier_analysis = (
    df.groupby(['Shipping carriers', 'Transportation modes'])
    .agg(
        avg_shipping_cost=('Shipping costs', 'mean'),
        avg_shipping_time=('Shipping times', 'mean'),
        total_shipments=('SKU', 'count'),
    )
    .reset_index()
)

print("\n--- Shipping Carrier and Mode Analysis ---")
print(carrier_analysis)


# -------------------------------------------------------------------
# STEP 4: Quality Control & Supplier Risk Metrics
# -------------------------------------------------------------------
supplier_quality = (
    df.groupby('Supplier name')
    .agg(
        avg_defect_rate=('Defect rates', 'mean'),
        avg_mfg_cost=('Manufacturing costs', 'mean'),
        pass_rate=('Inspection results', lambda x: (x == 'Pass').mean() * 100),
    )
    .reset_index()
)

print("\n--- Supplier Quality Performance ---")
print(supplier_quality)

# -------------------------------------------------------------------
# STEP 5: Visualizations
# -------------------------------------------------------------------
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Chart 1: Total Revenue by Product Type
sns.barplot(
    data=product_analysis,
    x='Product type',
    y='total_revenue',
    ax=axes[0, 0],
    palette='Set2',
)
axes[0, 0].set_title('Total Revenue Generated by Product Type')
axes[0, 0].set_ylabel('Revenue ($)')

# Chart 2: Defect Rates across Transportation Modes
sns.boxplot(
    data=df,
    x='Transportation modes',
    y='Defect rates',
    ax=axes[0, 1],
    palette='Set3',
)
axes[0, 1].set_title('Defect Rate Distribution by Transport Mode')

# Chart 3: Shipping Costs vs. Shipping Times
sns.scatterplot(
    data=df,
    x='Shipping times',
    y='Shipping costs',
    hue='Transportation modes',
    ax=axes[1, 0],
    s=100,
)
axes[1, 0].set_title('Shipping Cost vs. Shipping Time')

# Chart 4: Inspection Results Breakdown
inspection_counts = df['Inspection results'].value_counts()
axes[1, 1].pie(
    inspection_counts,
    labels=inspection_counts.index,
    autopct='%1.1f%%',
    colors=['#ff9999', '#66b3ff', '#99ff99'],
)
axes[1, 1].set_title('Quality Inspection Status')

plt.tight_layout()
plt.show()

# -------------------------------------------------------------------
# STEP 6: Feature Selection & Data Preparation
# -------------------------------------------------------------------
# Select all numerical predictor variables
numeric_cols = [
    'Price',
    'Availability',
    'Number of products sold',
    'Stock levels',
    'Lead times',
    'Order quantities',
    'Shipping times',
    'Shipping costs',
    'Lead time',
    'Production volumes',
    'Manufacturing lead time',
    'Manufacturing costs',
    'Defect rates',
    'Costs',
]

X = df[numeric_cols]
y = df['Revenue generated']

# -------------------------------------------------------------------
# STEP 7: Train/Test Split
# -------------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

# -------------------------------------------------------------------
# STEP 8: Model Initialization & Training
# -------------------------------------------------------------------
model = LinearRegression()
model.fit(X_train, y_train)

# -------------------------------------------------------------------
# STEP 9: Predictions & Model Evaluation
# -------------------------------------------------------------------
y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)

# Calculate evaluation metrics
r2_train = r2_score(y_train, y_pred_train)
r2_test = r2_score(y_test, y_pred_test)

mse_train = mean_squared_error(y_train, y_pred_train)
mse_test = mean_squared_error(y_test, y_pred_test)
rmse_test = np.sqrt(mse_test)

print(f'Train R2 Score: {r2_train:.4f}')
print(f'Test R2 Score:  {r2_test:.4f}')
print(f'Test MSE:        {mse_test:.2f}')
print(f'Test RMSE:       ${rmse_test:.2f}')

# -------------------------------------------------------------------
# STEP 10: Visualizing Actual vs. Predicted Revenue
# -------------------------------------------------------------------
plt.figure(figsize=(8, 5))
plt.scatter(
    y_test,
    y_pred_test,
    color='royalblue',
    edgecolors='k',
    alpha=0.8,
    label='Predicted vs Actual',
)
plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    'r--',
    lw=2,
    label='Perfect Prediction Line',
)
plt.xlabel('Actual Revenue Generated ($)')
plt.ylabel('Predicted Revenue Generated ($)')
plt.title('Linear Regression: Actual vs. Predicted Revenue (Test Set)')
plt.legend()
plt.tight_layout()
plt.show()
